### ISSUE TITLE
Add [skip ci] workaround to avoid obsolete builds

### ISSUE THREAD

**Issue by tillkuhn** [tillkuhn/angkor#12]
* [Support [skip ci] out of box with github actions](https://github.com/actions/runner/issues/774)
* Workaround: https://github.community/t/github-actions-does-not-respect-skip-ci/17325
* Marketplace: https://github.com/marketplace/actions/ci-skip-action

```
name: my CI github action

on:
  push:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
```
